config/routes.rb
Rails.application.routes.draw do
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	#get 'home', to: 'home#index'

	resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	#get
	def index
		@title = 'Tabel Data Buku'
		@books = Book.all
	end

	#get
	def show
		@title = 'Tabel Data Buku'
		@book = Book.find(params[:id])
	end
	
	#get
	def new
		@title = 'Form Add Book'
		@book  = Book.new
	end
	
	#post
	def create
		book = Book.new(resource_params)
		book.save

      	redirect_to books_path, notice: "Berhasil ditambahkan"
		#render plain: 'Success'
	end

	#get
	def edit
		@title = 'Form Edit Book'
		@book = Book.find(params[:id])
	end
	
	#patch/put
	def update
		@book = Book.find(params[:id])
		@book.update(resource_params)

      	redirect_to books_path, notice: "Berhasil diupdate"
		# render plain: 'Success'
	end

	#delete
	def destroy
		@book = Book.find(params[:id])
		@book.destroy

      	redirect_to books_path, notice: "Berhasil dihapus"
		# render plain: 'Success'
	end

	private
	def resource_params
		params.require(:book).permit(:title, :page, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<h3><%= @title %></h3>
<hr>
<%= form_for(@book) do |f| %>
	<div class="form-group">
		<%= f.label :Title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :Page %>
		<%= f.number_field :page, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :Description %>
		<%= f.text_area :description, class: 'form-control', rows: '4' %>
	</div>
	<div class="form-group">
		<%= f.submit nil, class: "btn btn-info" %>
	</div>
<% end %>

app/views/books/index.html.erb
<h3><%= @title %></h3>
<%= link_to "New Book", new_book_path, class: 'btn btn-primary btn-sm'%>
<hr>

<% flash.each do |type, message| %> <!-- memanggil notifikasi jika gagal login-->
	<p class="alert alert-success alert-dismissable fade show"><button type="button" class="close" data-dismiss="alert">&times;</button>
	<strong>Success! </strong><%=message%></p>
<%end%> 

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>No</th>
			<th>Title</th>
			<th>Page</th>
			<th>Desctiption</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% no=1; @books.each do |book| %>
		<tr>
			<td><%= no %></td>
			<td><%= book.title %></td>
			<td><%= book.page %></td>
			<td><%= book.description %></td>
			<td>
				<%= link_to "Show", book_path(book.id), class: 'btn btn-info btn-sm' %> |
				<%= link_to "Edit", edit_book_path(book.id), class: 'btn btn-secondary btn-sm'%> |
				<%= link_to "Delete", book_path(book.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm' %>
			</td>
		</tr>
		<% no+=1 end %>
	</tbody>
</table>

app/views/books/new.html.erb
<h3><%= @title %></h3>
<hr>
<%= form_for(@book) do |f| %>
	<div class="form-group">
		<%= f.label :Title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :Page %>
		<%= f.number_field :page, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :Description %>
		<%= f.text_area :description, class: 'form-control', rows: '4' %>
	</div>

	<div class="form-group">
		<%= f.submit nil, class: "btn btn-info" %>
	</div>
<% end %>

app/views/books/show.html.erb
<%= link_to "Back", books_path, class: 'btn btn-info btn-sm' %>
<table>
	<tr>
		<td>Title</td>
		<td>: <%=@book.title%></td>
	</tr>
	<tr>
		<td>Page</td>
		<td>: <%=@book.page%></td>
	</tr>
	<tr>
		<td>Description</td>
		<td>: <%=@book.description%></td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD-Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h3>Program CRUD - ruby on rails</h3>
      <%= yield %>
    </div>
  </body>
</html>